#!/bin/sh
set -e
if [ "$1" = remove ]; then systemctl stop epg-stream.service >/dev/null 2>&1 || true; fi
if [ "$1" = remove ]; then systemctl disable --now epg-stream-updater.path >/dev/null 2>&1 || true; fi
exit 0
